Addview
shoichinishiguchi/chat-space pull request #4
Opened 2019-03-31 12:25 UTC by shoichinishiguchi

WHAT
ビューを作った。
WHY
ビューの見栄えを整えて見やすくする為

2019-03-31 12:27 UTC, shoichinishiguchi commented
<img width="1440" alt="スクリーンショット 2019-03-31 21 23 32" src="https://user-images.githubusercontent.com/48884623/55289024-af08d880-53fb-11e9-932a-ce0287c27ec0.png">

2019-03-31 12:40 UTC, ghost requested changes

2019-03-31 12:40 UTC, hiroki5123 commented on app/controllers/messages_controller.rb
> +def index
インデント一個奥です！

2019-03-31 12:40 UTC, hiroki5123 commented on app/views/messages/index.html.haml
> +    %i.fa.fa-pencil-square-o.icon
ulの配下はli要素である必要があります

2019-03-31 12:40 UTC, hiroki5123 commented on config/routes.rb
> +root 'messages#index'
インデント一個奥です

2019-03-31 13:46 UTC, shoichinishiguchi commented
細かいところまで見ていただきありがとうございます。
基本的な部分で申し訳ありません。
全て修正しました！

2019-04-01 02:03 UTC, TOMARUMARU approved these changes
LGTM

2019-04-01 05:21 UTC, shoichinishiguchi commented
ありがとうございました！！！

2019-04-01 05:22 UTC, merged